### ISSUE TITLE
Variable 'ResourceManager' implicitly declared.

### ISSUE THREAD

**Issue by leeyeh** [tbfe/bigpipe.js#2]
#### Occurred on:
- **Commit**:  e850a0629ceff4b2f6d898497a623ad43aaa1ce8
- **File**:    [lib/bigpipe.js](https://github.com/tbfe/bigpipe.js/blob/e850a0629ceff4b2f6d898497a623ad43aaa1ce8/lib/bigpipe.js)
- **LineNum**: [723](https://github.com/tbfe/bigpipe.js/blob/e850a0629ceff4b2f6d898497a623ad43aaa1ce8/lib/bigpipe.js#L723)
- **Code**:    `ResourceManager = options.ResourceManager;`
#### Currently on:
- **Commit**:  8c25b633a689066d7777b4b6670a6f4347e7f75e
- **File**:    [lib/bigpipe.js](https://github.com/tbfe/bigpipe.js/blob/8c25b633a689066d7777b4b6670a6f4347e7f75e/lib/bigpipe.js)
- **LineNum**: [677](https://github.com/tbfe/bigpipe.js/blob/8c25b633a689066d7777b4b6670a6f4347e7f75e/lib/bigpipe.js#L677)

**Comment by naiteluo** [comment]
Codacy saigo~~ i will fix it!
